### ISSUE TITLE
episodes not recognized

### ISSUE THREAD

**Issue by thrillfall** [einmalfel/PodListen#11]
I added the feed: http://www.radioeins.de/archiv/podcast/zwei_alte_hasen.feed.podcast.xml, but podlisten never showed me any new episodes. Also when adding the feed and setting to import all episodes or all of the last month does not come up with anything.

Have i missed anything?

**Comment by einmalfel** [comment]
@thrillfall Thanks for pointing this out. My bad. Will be fixed in upcoming update.

**Comment by einmalfel** [comment]
Fixed in version 1.2.5. It will become available on Google Play within few hours and on F-Droid in a day or two.
