### ISSUE TITLE
Podcast URL emptied from input when rotating device

### ISSUE THREAD

**Issue by morganestes** [einmalfel/PodListen#13]
When I add a podcast in portrait mode and rotate the device before saving, the feed URL input field empties itself. Rotating it back doesn't restore the URL.

**Comment by einmalfel** [comment]
@morganestes Thanks for reporting, fixed in update 1.3.2

**Comment by morganestes** [comment]
@einmalfel Thanks for the quick response! I just updated and confirmed that this bug's fixed. :thumbsup:
