### ISSUE TITLE
Episodes in "New Episodes" view should be sorted in feed order

### ISSUE THREAD

**Issue by lutostag** [einmalfel/PodListen#15]
First off, thanks for making a quick and usable podcast client. The one use-case I am missing is for audiobooks from librivox.org. Typically I have the episodes to auto-download only when "Episodes are added to playlist" as I don't want all 1.43GB of a large book like https://librivox.org/the-count-of-monte-cristo-by-alexandre-dumas-2/ to download all at once. So if the episodes could be sorted in the given feed order (http://librivox.org/rss/6263) even if pubDate is not set in the given feed that would be helpful (otherwise searching through the random order to find the next chapter is a bit of a chore).

Thanks!

**Comment by einmalfel** [comment]
Hello, @lutostag 
Update 1.3.3 (which will become available on Google Play in a few hours and F-Droid in a day or two) fixes sort order of episodes without pubDate both in "new episodes" tab and in "episodes of feed" dialog.
