### ISSUE TITLE
Enhancement request: retrieve feed URLs from web pages

### ISSUE THREAD

**Issue by rmenessec** [einmalfel/PodListen#16]
Would it be possible to pull podcast feed URIs from web pages, along the lines of the feed detection Firefox can perform? Most sites don't adhere to any particular standard for placing, naming, or listing feed URIs, making it a pain to find, copy, and enter each syndication URI manually.

Anything PodListen could do to automate this would be great.

Thanks!

**Comment by einmalfel** [comment]
Hi, @rmenessec 

I've [just implemented](cbd288435b1d07f7eab2a22c1333d943fb026357) this feature 9 hours ago :)
Update (v1.3.4) is available on Google Play and will become available on F-Droid in a day or two.

This feature probably doesn't work for all podcast web pages initially. Please, let me know if it fails for some web-page, I'll fix it

**Comment by rmenessec** [comment]
Oh. I just updated a few minutes ago.

Thanks so much!
