### ISSUE TITLE
Enhancement: Remember accessed episodes

### ISSUE THREAD

**Issue by bugmenot2** [einmalfel/PodListen#19]
Now that we have a complete podcast episodes list available, it would be useful to know which episodes were listened to / downloaded / added to the playlist before.Won't take much speace per podcast, may perhaps be forgotten when the podcast is removed.

**Comment by bugmenot2** [comment]
Just read through the readme but... I still hope.

**Comment by einmalfel** [comment]
@bugmenot2 
Agreed, this will make feed history more informative if episodes never listened to will be emphasized.
I'd designate listened episodes by graying them out (but leaving "add" button bright) like on screenshot below. What do you think?

![device-2015-11-28-171642](https://cloud.githubusercontent.com/assets/2640813/11452294/da8ad338-95f3-11e5-9c53-61335077b9dc.png)

**Comment by bugmenot2** [comment]
Looking forward to the update.

**Comment by bugmenot2** [comment]
Still no update? Why? :-(
*keeps refreshing f-droid*

**Comment by einmalfel** [comment]
Sorry! Had no time for PodListen during last couple of weeks. Will push small update including this feature by the end of this week.

**Comment by einmalfel** [comment]
I've published the update. There will be usual delay on F-Droid site.

NB: PodListen will consider all episodes it already knows about as "accessed".

**Comment by bugmenot2** [comment]
*mumble grumble*
