### ISSUE TITLE
"Play next episode in playlist" makes episodes unrepeatable

### ISSUE THREAD

**Issue by jordanl** [einmalfel/PodListen#2]
If "Play next episode in playlist" is enabled, then once episode A finishes playing PodListen will jump to epsode B, but leave episode A at 100% such that tapping on A again will automatically jump to B. At this point it's impossible to replay episode A.

**Comment by einmalfel** [comment]
Thanks for pointing this out!
Fix will become available on Google Play within a few hours and F-Droid within 24 hours.
Please let me know if it still glitches after update.
