### ISSUE TITLE
feature request: Lockscreen Controls

### ISSUE THREAD

**Issue by paskalito** [einmalfel/PodListen#21]
the thing i would like to have most while using the app to actually listen to podcast is to start and stop and maybe jump back my 30 sex from lockscreen. for everytime someone starts talking to me why im listening or the train arrives or departs or something elso noisy happens.

yould just make it a lot quicker :)

**Comment by einmalfel** [comment]
@paskalito Heh, this feature is in my TODO list from the first day of PodListen existence :) Sadly, PodListen's player service is badly designed, and I need to rework it first, before implementing lockscreen controls. Be patient, I'll do it eventually :)

**Comment by paskalito** [comment]
hey thats cool :)
so i know im not alone, and someones coming to help ^^ - i will be happily surprised once its suddenly there .. :person_with_blond_hair:

**Comment by haxwithaxe** [comment]
this feature appears to be implemented in 1.3.6. sorry if this is a double post, I'm not seeing my previous fat fingered post.

**Comment by paskalito** [comment]
actually that's true :D - so i close the isssue :D 
thank you 🎉
