### ISSUE TITLE
Can't undo mark-all-as-read

### ISSUE THREAD

**Issue by DamienCassou** [einmalfel/PodListen#3]
I've just pressed this shiny orange stair-like button next to my podcasts. All the potcasts disappeared, with no way to cancel and no confirmation button

**Comment by einmalfel** [comment]
I agree, this is very inconvenient. I am going to add "undo" button to snackbar

**Comment by einmalfel** [comment]
Done in version 1.2.3, which is now live on Google Play and will be available on F-Droid within 24 hours.
