### ISSUE TITLE
Feature request: allow change 'how much episodes to add' for subscription list

### ISSUE THREAD

**Issue by QiangF** [einmalfel/PodListen#38]
Hi everyone,
Does any of you want to change the setting of amount of episodes to fetch for a subscription? Currently you have to unsubscribe and resubscribe, because the setting is only available at the subscribing interface. 
Thank you!

**Comment by einmalfel** [comment]
Hello, @QiangF 
There is no need to resubscribe. When you subscribe first time, whole feed is fetched, and amount of episodes specified in "how much episodes to add" is added to "new episodes" tab. After then, you can add any known episode (regardless of "how much episodes to add" setting) to playlist in "episode list" dialog.

**Comment by QiangF** [comment]
@einmalfel  I mean to change the amount of episodes to fetch after subscription in case you did it wrong the first time. If you mean the "episode list" dialog in the subscription tab, the amount of episode displayed can't be changed, eg. if you set the amount to 10, but you want it to display older podcast, I can't find a way to do that.
Thank you for your consideration.

**Comment by QiangF** [comment]
OK. I see. There is no more.
