### ISSUE TITLE
request: pause on headset disconnect

### ISSUE THREAD

**Issue by martian742** [einmalfel/PodListen#4]
I know this app has to stay lightweight, but I really miss being able to pause playback upon yanking the headphones from my phone or switching off/loosing signal on a bluetooth headset.

**Comment by einmalfel** [comment]
Agreed, this is must-have feature. You can expect update that brings this feature to become available on next week.

**Comment by einmalfel** [comment]
Feature was added in version 1.2.3 which is now live on Google Play and will be available on F-Droid within 24 hours.
See options -> playback -> pause on headphones disconnect
