### ISSUE TITLE
No 'delete episode and do nothing'  option in Playback Complete. 

### ISSUE THREAD

**Issue by cdysthe** [einmalfel/PodListen#7]
There's no 'delete episode and do nothing' option in the Playback Complete settings. Very surprising in a nearly perfect podcast player.

**Comment by einmalfel** [comment]
It should be easy to fix, I'll add the option during this weekend.
If you have a pair of spare minutes, could you please explain your usage pattern and why do you need this option? Cause I can't imagine a reason of using it instead of "delete and play next".

**Comment by einmalfel** [comment]
@cdysthe 
I have added the option.
Update (v1.2.3) is live on Google Play and will be available on F-Droid within 24 hours.

**Comment by cdysthe** [comment]
Hi,

Great! The reason for wanting that is that I have lots of podcasts I subscribe to, and I often start an episode and just want to listen to just one episode and not start a new one. I often put my phone down and move around and simply forget to stop playback, so having it stop and delete is the way I like it to work.

**Comment by einmalfel** [comment]
@cdysthe One more question: if I add sleep timer, will you use it or will you still use "delete and do nothing" option?
